--ASSIGNMENT 5
--A5B

--PROBLEM 1
SELECT	EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL
FROM	EMPLOYEEC
WHERE	EMP_LNAME LIKE 'SMITH%'
ORDER BY EMP_NUM

--PROBLEM 2
SELECT	P.PROJ_NAME, P.PROJ_VALUE, P.PROJ_BALANCE, E.EMP_LNAME, E.EMP_FNAME, E.EMP_INITIAL, J.JOB_CODE, J.JOB_DESCRIPTION, J.JOB_CHG_HOUR
FROM	PROJECT P INNER JOIN EMPLOYEEC E ON P.EMP_NUM = E.EMP_NUM
		INNER JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
ORDER BY P.PROJ_VALUE

--PROBLEM 3
SELECT	P.PROJ_NAME, P.PROJ_VALUE, P.PROJ_BALANCE, E.EMP_LNAME, E.EMP_FNAME, E.EMP_INITIAL, J.JOB_CODE, J.JOB_DESCRIPTION, J.JOB_CHG_HOUR
FROM	PROJECT P INNER JOIN EMPLOYEEC E ON P.EMP_NUM = E.EMP_NUM
		INNER JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
ORDER BY E.EMP_LNAME

--PROBLEM 4
SELECT DISTINCT	PROJ_NUM
FROM		ASSIGNMENT
ORDER BY	PROJ_NUM

--PROBLEM 5
SELECT	ASSIGN_NUM, EMP_NUM, PROJ_NUM, ASSIGN_CHARGE, ASSIGN_CHG_HR * ASSIGN_HOURS AS 'CALC_ASSIGN_CHARGE'
FROM	ASSIGNMENT
ORDER BY ASSIGN_NUM

--PROBLEM 6
SELECT	E.EMP_NUM, E.EMP_LNAME, ROUND(SUM(A.ASSIGN_HOURS),1) AS 'SumOfASSIGN_HOURS', ROUND(SUM(A.ASSIGN_CHARGE),2) AS 'SumOfASSIGN_CHARGE'
FROM	ASSIGNMENT A INNER JOIN EMPLOYEEC E ON A.EMP_NUM = E.EMP_NUM
GROUP BY E.EMP_NUM, E.EMP_LNAME

--PROBLEM 7
SELECT	A.PROJ_NUM, ROUND(SUM(ASSIGN_HOURS),1) AS 'SumOfASSIGN_HOURS', ROUND(SUM(ASSIGN_CHARGE),2) AS 'SumOfASSIGN_CHARGE'
FROM	ASSIGNMENT A 
GROUP BY A.PROJ_NUM

--PROBLEM 8
SELECT	ROUND(SUM(ASSIGN_HOURS),1) AS 'SumOfASSIGN_HOURS', ROUND(SUM(ASSIGN_CHARGE),2) AS 'SumOfASSIGN_CHARGE'
FROM	ASSIGNMENT
